---
title: "Solar Radiation"
format: html
---

```{r}
library(terra)
library(raster)
library(tmap)
library(RColorBrewer)
```

```{r}
slope <- raster(here::here("~/../../capstone/milkweedmod/clean_data/dem/lpnf_slope.tif"))
aspect <- raster(here::here("~/../../capstone/milkweedmod/clean_data/dem/lpnf_aspect.tif"))

lpnf_south <- sf::st_read(here::here("~/../../capstone/milkweedmod/data/lpnf_boundary_data/lpnf_boundary_south/lpnf_boundary_south.shp"))

dem <- raster(here::here("~/../../capstone/milkweedmod/clean_data/dem/lpnf_dem.tif"))
dem_aspect <- terra::terrain(dem, v = "aspect", unit="degrees")

```


```{r}
# Obtain DEM derived maps
derived_vars <- terrain(dem, opt = c('slope', 'aspect'), unit = "degrees")
slope <- derived_vars[["slope"]]
northness <- cos(derived_vars[["aspect"]] * pi / 180) * sin(derived_vars[["slope"]] * pi / 180)
eastness <- sin(derived_vars[["aspect"]] * pi / 180)

# Plot maps
plot(northness, col = heat.colors(20), main = "northness", axes = F)
plot(eastness, col = heat.colors(20), main = "eastness", axes = F)
```


“Northness”: Cosine of aspect x sine of slope
- If facing due south, cosine of aspect = 1
- As slope gets steeper, sine of slope increases
- South facing vertical wall has a northness of -1
- If want to change to “southness” multiply by -1 for positive values
- North facing vertical wall has a northness of 1

```{r}
plot(eastness, col = heat.colors(20), main = "eastness", axes = F)
plot(northness, col = heat.colors(20), main = "northness", axes = F)

```

“eastness” (sine(aspect) x sine(slope))
- If due east on a vertical wall –> 1

```{r}
eastness <- sin(aspect) * sin(slope)
```

Write rasters
```{r}
 # writeRaster(northness, here::here("~/../../capstone/milkweedmod/clean_data/dem/northness.tif"), overwrite=TRUE)
 # writeRaster(eastness, here::here("~/../../capstone/milkweedmod/clean_data/dem/eastness.tif"), overwrite=TRUE)
```


```{r}
# plotting to make sure northness and eastness look correct
bbox <- sf::st_bbox(c(xmin = -120.2, ymin = 34.8, xmax = -120, ymax = 35),  crs = sf::st_crs(4326))

northness_crop <- crop(northness, bbox)

plot(northness_crop,  col = palette(brewer.pal(n = 9, name = "Greys")), main = "northness")
```


```{r}
northness_vals <- northness@data@values %>% 
  data.frame() %>%
  drop_na()
head(northness_vals, n = 20)
```

