---
author: "Anna Ramji"
title: "Milkweed Subsets & Polygons to Points"
---


```{r setup}
# load required packages
library(tidyverse)
library(janitor)
library(sf)
library(ggspatial)
library(terra)
library(here)
library(leaflet)
library(plotly)
library(rnaturalearth)
library(rnaturalearthdata)

# read in data

milkweed_path <- here("~/../../capstone/milkweedmod/data/milkweed_polygon_data/")

milkweed_data_raw <- st_read(milkweed_path)

```



```{r subsets}
# remove "No" observations
milkweed_presence <- milkweed_data_raw |> 
  janitor::clean_names() |> 
  filter(milkweed_p != "no")

# subset per species

# Asclepias californica
californica <- milkweed_presence |> 
  filter(milkweed_sp %in% c("Asclepias californica")) # 48 observations

# Asclepias eriocarpa
eriocarpa <- milkweed_presence |> 
  filter(milkweed_sp %in% c("Asclepias eriocarpa")) # 116 observations

erosa <- milkweed_presence |> 
  filter(milkweed_sp %in% c("Asclepias erosa")) # only 5 observations

vestita <- milkweed_presence |> 
  filter(milkweed_sp %in% c("Asclepias vestita")) # only 7 observations


```


```{r}

all_spec_subset <- milkweed_presence |> 
  select(milkweed_sp, geometry)

all_spec_centroids <- st_centroid(all_spec_subset)



# st_crs(all_spec_centroids)
# epsg 3857

# all_spec_points <- writeRaster(all_spec_centroids, "")

```


