---
title: "DEM"
author: "Sam Muir"
---

This notebook combines all tiles into one DEM raster that covers the entire area of the LPNF.

Data is from the USGS National Map
- 3DEP 1 arc-second DEM current

```{r}
library(tidyverse)
library(raster)
library(terra)
library(tidyterra)
library(here)

# Define base directory file path
base_dir <- here::here("~/Library/CloudStorage/Box-Box/MEDS-SBBG-milkweed")
```

```{r}
# set file path
file_path <- here(base_dir, "raw_data", "dem")

# read in dem data tiles
n35w119 <- rast(here(file_path, "USGS_1_n35w119_20190919.tif"))
n35w120 <- rast(here(file_path, "USGS_1_n35w120_20190924.tif"))
n35w121 <- rast(here(file_path, "USGS_1_n35w121_20190924.tif"))
n36w120 <- rast(here(file_path, "USGS_1_n36w120_20190919.tif"))
n36w121 <- rast(here(file_path, "USGS_1_n36w121_20190919.tif"))
n36w122 <- rast(here(file_path, "USGS_1_n36w122_20210301.tif"))
n37w122 <- rast(here(file_path, "USGS_1_n37w122_20201207.tif"))
```

```{r}
# mosaic the tiles to get full area
dem <- mosaic(n35w119, n35w120, n35w121, n36w120, n36w121, n36w122, n37w122)
plot(dem)
```

```{r}
# writeRaster(dem, here(data_dir, "data", "dem", "lpnf_dem.tif"))
```

