---
title: "LPNF Boundary and Trails/Roads"
author: "Amanda"
---

Load packages
```{r}
library(tidyverse)
library(sf)
library(here)
```

## Read in CA National Forest boundaries
```{r}
# California National Forest boundaries
boundary <- st_read(here("~/../../capstone/milkweedmod/raw_data/S_USA_AdministrativeForest.gdb/"))
```

## Filter boundaries to Los Padres National Forest
```{r}
lpnf_boundary <- boundary %>% 
  filter(FORESTNAME %in% c("Los Padres National Forest")) %>%
  st_transform(crs = st_crs("EPSG:4326"))

# save a buffered boundary for species distribution modeling
forest_buffer <- lpnf_boundary  %>%
  st_buffer(dist = 1000)

# save boundaries as shapefiles

# st_write(lpnf_boundary,
#          here("~/../../capstone/milkweedmod/cleandata/lpnf_boundary/lpnf_boundary/lpnf_boundary.shp"),
#          append = FALSE)
# st_write(forest_buffer,
#         here("~/../../capstone/milkweedmod/clean_data/lpnf_boundary/lpnf_boundary_buffered/lpnf_boundary_buffered.shp"),
#         append = FALSE)
 
```

## Separate LPNF boundary into northern and southern sections

Finding max-y for southern section by visualizing
```{r}
ggplot() +
  geom_sf(data = forest_buffer)

# select 35.6 as max-y for subsection of southern portion! 
```

```{r}
# Create a bounding box for the south and north
bbox_south <- st_bbox(c(xmin = -118, ymin = 34.2, xmax = -121, ymax = 35.5),  crs = st_crs(4326))
bbox_north <- st_bbox(c(xmin = -122, ymin = 35.5, xmax = -121, ymax = 36.5),  crs = st_crs(4326))

# Crop boundary to the bounding boxes
lpnf_south <- st_crop(lpnf_boundary, bbox_south) %>%
  select(SHAPE)
lpnf_north <- st_crop(lpnf_boundary, bbox_north) %>% 
  select(SHAPE)

# create buffered boundaries for south and north
lpnf_south_buffered <- lpnf_south %>%
  st_buffer(dist = 1000)
lpnf_north_buffered <- lpnf_north %>%
  st_buffer(dist = 1000)
```

Plot to verify 
```{r}
lpnf_south_df <- lpnf_south %>%
  st_coordinates() %>%
  data.frame()

ggplot(lpnf_south_df) +
  geom_polygon(aes(x = X, y = Y))

ggplot() +
  geom_sf(data = lpnf_south, color = "green4")
```

Save boundaries as shapefiles
```{r}
# write the forest boundaries
# st_write(lpnf_north, here("~/../../capstone/milkweedmod/clean_data/lpnf_boundary/lpnf_boundary_north/lpnf_boundary_north.shp"), append = FALSE)
# st_write(lpnf_south, here("~/../../capstone/milkweedmod/clean_data/lpnf_boundary/lpnf_boundary_south/lpnf_boundary_south.shp"), append = FALSE)
# st_write(lpnf_north_buffered, here("~/../../capstone/milkweedmod/clean_data/lpnf_boundary/lpnf_boundary_north_buffered/lpnf_boundary_north_buffered.shp"), append = FALSE)
# st_write(lpnf_south_buffered, here("~/../../capstone/milkweedmod/clean_data/lpnf_boundary/lpnf_boundary_south_buffered/lpnf_boundary_south_buffered.shp"), append = FALSE)
```

