---
title: "Solar Radiation"
format: html
---

```{r}
library(terra)
library(tmap)
library(RColorBrewer)
```

```{r}
dem <- rast(here("~/../../capstone/milkweedmod/data/dem/lpnf_dem.tif"))
slope <- raster(here::here("~/../../capstone/milkweedmod/data/dem/lpnf_slope.tif"))
aspect <- raster(here::here("~/../../capstone/milkweedmod/data/dem/lpnf_aspect.tif"))

lpnf_south <- st_read(here("~/../../capstone/milkweedmod/data/lpnf_boundary_data/lpnf_boundary_south/lpnf_boundary_south.shp"))
```

“Northness”: Cosine of aspect x sine of slope
- If facing due south, cosine of aspect = 1
- As slope gets steeper, sine of slope increases
- South facing vertical wall has a northness of -1
- If want to change to “southness” multiply by -1 for positive values
- North facing vertical wall has a northness of 1

```{r}
northness <- cos(aspect * (180 / pi)) * sin(slope * (180 / pi))
```

“eastness” (sine(aspect) x sine(slope))
- If due east on a vertical wall –> 1

```{r}
eastness <- sin(aspect * (180 / pi)) * sin(slope * (180 / pi))
```

```{r}
# crop northness to southern ext
northness_lpnfS <- crop(northness, lpnf_south, mask = TRUE)

plot(northness_lpnfS, col = palette(brewer.pal(n = 11, name = "RdBu")), main = "Northness - LPNF South Section")
plot(northness, col = palette(brewer.pal(n = 11, name = "RdBu")), main = "Northness")

# crop eastness to southern ext
eastness_lpnfS <- crop(eastness, lpnf_south, mask = TRUE)

plot(eastness_lpnfS, col = palette(brewer.pal(n = 11, name = "RdBu")), main = "Eastness - LPNF South Section")
plot(eastness, col = palette(brewer.pal(n = 11, name = "RdBu")), main = "Eastness")
```


