---
title: "Milkweed Subsets & Polygons to Points"
date-modified: "2024-05-22"
---

This notebook subsets the milkweed polygon data, creates centroids, and exports files for each species. 

```{r setup}
# load required packages
library(tidyverse)
library(janitor)
library(sf)
library(ggspatial)
library(terra)
library(here)
library(leaflet)
library(plotly)
library(rnaturalearth)
library(rnaturalearthdata)

# read in data

milkweed_path <- here("~/../../capstone/milkweedmod/raw_data/milkweed_polygon_data/")

milkweed_data_raw <- st_read(milkweed_path)

```



```{r subsets}
# remove "No" observations
milkweed_presence <- milkweed_data_raw |> 
  janitor::clean_names() |> 
  filter(milkweed_p != "no")

# subset per species

# Asclepias californica
californica <- milkweed_presence |> 
  filter(milkweed_sp %in% c("Asclepias californica")) # 48 observations

# Asclepias eriocarpa
eriocarpa <- milkweed_presence |> 
  filter(milkweed_sp %in% c("Asclepias eriocarpa")) # 116 observations

erosa <- milkweed_presence |> 
  filter(milkweed_sp %in% c("Asclepias erosa")) # only 5 observations

vestita <- milkweed_presence |> 
  filter(milkweed_sp %in% c("Asclepias vestita")) # only 7 observations

```


```{r}
# ------------------- Creating Centroids --------------------------------------

all_spec_subset <- milkweed_presence |> 
  select(milkweed_sp, geometry)

all_spec_centroids <- st_centroid(all_spec_subset)
```


```{r, eval=FALSE}
# ----------- Optional -- Creating species-specific centroids, including number of plants ---------------------
californica_centroids <- californica |> 
  select(milkweed_sp, # species name
         milkweed_pl, # number of plants
         geometry) |> # associated geometries (geometries are automatically retained whenever you manipulate a special feature, but I'm specifying it to be overly clear for reproducibility )
  st_centroid() # creates one point in the center of each geometry 

eri_centroids <- eriocarpa |> 
  select(milkweed_sp, # species name
         milkweed_pl, # number of plants
         geometry) |> # associated geometries (geometries are automatically retained whenever you manipulate a special feature, but I'm specifying it to be overly clear for reproducibility )
  st_centroid() # creates one point in the center of each geometry 

erosa_centroids <- erosa |> 
  select(milkweed_sp, # species name
         milkweed_pl, # number of plants
         geometry) |> # associated geometries (geometries are automatically retained whenever you manipulate a special feature, but I'm specifying it to be overly clear for reproducibility )
  st_centroid() # creates one point in the center of each geometry 

vestitia_centroids <- vestita |> 
  select(milkweed_sp, # species name
         milkweed_pl, # number of plants
         geometry) |> # associated geometries (geometries are automatically retained whenever you manipulate a special feature, but I'm specifying it to be overly clear for reproducibility )
  st_centroid() 


```


```{r, eval=FALSE}
# checking crs
# st_crs(all_spec_centroids)
# epsg 3857
# ------------ Writing data to new files in Taylor ----------------------------

all_spec_points <- st_write(all_spec_centroids, "~/../../capstone/milkweedmod/data/milkweed_cleaned_data/points/all_species_points.shp")
write_rds(all_spec_centroids, "outputs/dashboard/all_species_points.rda")
```


