---
title: "Max suitability"
author: "Sam Muir"
format: html
---

This notebook contains code to find the maximum suitability across all four milkweed species, and maps these highest values of prediction in the LPNF. The SDM .tif files being read in were generated from four different notebooks: A_californica_sdm.qmd, A_eriocarpa_sdm.qmd, A_erosa_sdm.qmd, A_vestita_sdm.qmd. 

```{r}
# Define base directory file path
base_dir <- here::here("~/Library/CloudStorage/Box-Box/MEDS-SBBG-milkweed")

library(here)
library(terra)
library(leaflet)
source("R/addLegend_decreasing.R")
```

```{r}
# read in species sdm rasters
vestita <- raster(here("outputs", "dashboard", "vestita_sdm.tif"))
eriocarpa <- raster(here("outputs", "dashboard", "eriocarpa_sdm.tif"))
erosa <- raster(here("outputs", "dashboard", "erosa_sdm.tif"))
californica <- raster(here("outputs", "dashboard", "californica_sdm.tif"))

# read in lpnf boundary
lpnf_boundary <- st_read(here(base_dir, "clean_data", "lpnf_boundary", "lpnf_boundary", "lpnf_boundary.shp"))
```

```{r}
# stack all sdms
all_species <- stack(vestita, eriocarpa, erosa, californica)

# find the maximum value across all 4
max_suitable <- max(all_species)
```

```{r}
#Define colors and legend  
mapPredVals_Ac <- getRasterVals(max_suitable, "cloglog") # change for different types
rasCols <- c("#2c7bb6", "#abd9e9", "#ffffbf", "#fdae61", "#d7191c")
legendPal <- colorNumeric(rasCols, mapPredVals_Ac, na.color = 'transparent')
rasPal <- colorNumeric(rasCols, mapPredVals_Ac, na.color = 'transparent')

# plot
leaflet() %>% addProviderTiles(providers$Esri.WorldTerrain) %>%
  addLegend_decreasing("bottomleft", pal = legendPal, values = mapPredVals_Ac,
                       labFormat = reverseLabel(), decreasing = TRUE,
                       title = "<em>Asclepias sp.</em> Maximum<br> Predicted Suitability<br>") %>%
  addRasterImage(max_suitable, colors = rasPal, opacity = 0.7,
                 group = 'vis', layerId = 'mapPred', method = "ngb") %>%
  addPolygons(data = lpnf_boundary,
              fill = FALSE,
              color = "black",
              weight = 2)

# write locally, push to github
writeRaster(max_suitable, "outputs/dashboard/max_suitable_sdm.tif")
```

