---
title: "Canopy Cover"
author: "Melissa Widas"
---

This notebook combines all canopy cover tiles into one raster that covers the whole area of the LPNF.

## Load in Data
```{r}
# load packages
library(tidyverse)
library(raster)
library(terra)
library(here)
library(stars)

# Define base directory file path
base_dir <- here::here("~/Library/CloudStorage/Box-Box/MEDS-SBBG-milkweed")
canopy_dir <- here(base_dir, "raw_data", "canopy_cover")

```

```{r}
# Prepare milkweed data using raster package -----

# read in canopy cover data tiles
kern_county <- rast(here(canopy_dir, "KernCounty-Vegetation-CanopyCover-2020-Summer-00010m.tif"))

los_angeles_county <- rast(here(canopy_dir, "LosAngelesCounty-Vegetation-CanopyCover-2020-Summer-00010m.tif"))

monterey_county <- rast(here(canopy_dir, "MontereyCounty-Vegetation-CanopyCover-2020-Summer-00010m.tif"))

san_luis_obispo_county <- rast(here(canopy_dir, "SanLuisObispoCounty-Vegetation-CanopyCover-2020-Summer-00010m.tif"))

santa_barbara_county <- rast(here(canopy_dir, "SantaBarbaraCounty-Vegetation-CanopyCover-2020-Summer-00010m.tif"))

ventura_county <- rast(here(canopy_dir, "VenturaCounty-Vegetation-CanopyCover-2020-Summer-00010m.tif"))
```

## Initial Data Exploration
```{r}
# check to see how kern county plots
plot(kern_county)
```
```{r}
# check crs of kern county
st_crs(kern_county)
```


```{r}
# check resolution
res(kern_county)
```

## Combine data into 1 SpatRaster
```{r}
# combine rasters into a single raster for canopy cover
canopy_cover_full <- mosaic(kern_county, los_angeles_county, monterey_county, san_luis_obispo_county, santa_barbara_county, ventura_county)
# # combine rasters into a single raster for canopy cover using stars objects
# canopy_cover_full_s <- st_mosaic(kern_county_s, los_angeles_county_s, monterey_county_s, san_luis_obispo_county_s, santa_barbara_county_s, ventura_county_s)
```

```{r}
plot(canopy_cover_full)
```

```{r}
# resolution of canopy cover full is 10x10
res(canopy_cover_full)

# crs of canopy cover is EPSG 32610
crs(canopy_cover_full)
```


## Explore BioClim Data
```{r}
# Read in bioclim data
envs_Ac <- brick(here(base_dir, "clean_data", "bioclim", "wallace_bioclim.tif"))

# resolution of bioclim data is 0.008333333 0.008333333
res(envs_Ac)

# crs of bioclim is EPSG 9122
crs(envs_Ac)
```

## Get Canopy Cover and BioClim into same CRS
```{r}
canopy_cover_full_reproject <- project(canopy_cover_full,
                                       crs(envs_Ac),
                                       res = res(envs_Ac))
crs(canopy_cover_full_reproject)

# res of canopy_cover_reproject is  0.008333333 0.008333333
res(canopy_cover_full_reproject)

# returns TRUE
st_crs(envs_Ac) == st_crs(canopy_cover_full_reproject)
```

```{r}
plot(canopy_cover_full_reproject)
```

```{r}
plot(envs_Ac)
```


```{r}
# current layer name:
names(canopy_cover_full_reproject)

# rename layer name from KernCounty-Vegetation-CanopyCover-2020-Summer-00010m to "canopy_cover_percent"
names(canopy_cover_full_reproject) <- "canopy_cover_percent"

# check output
names(canopy_cover_full_reproject)
```


```{r}
# write renamed output to appropriate folder
writeRaster(canopy_cover_full_reproject,
            here(base_dir, "clean_data", "canopy_cover", "canopy_cover_cleaned.tif"),
            overwrite = TRUE) # If file with this name already exists, overwrite it
```





